steps:
  - label: create-pipeline
    command: "docker run -it ghcr.io/equinixmetal-buildkite/dynamic-buildkite-template:latest --overrides command=\'echo \"$COSIGN_KEY_SECRET\" > ${COSIGN_KEY_PATH}\'"
