steps:
  - label: my-step
    command: ls
    plugins:
      - improbable-eng/docker-service#v0.3.0:
          container: devopscounsel/dt:v1
    artifact_paths:
      - "docker-service.logs"
    command: "buildkite-agent artifact download \"docker-service.logs\" . &&  cat docker-service.logs | buildkite-agent pipeline upload"
