steps:
  - label: create-pipeline
    command: "docker run -it  devopscounsel/dt:v1 -h && docker run -it  devopscounsel/dt:v1 trivy > abc.txt && echo hello && cat abc.txt && docker run -it  devopscounsel/dt:v1 trivy | buildkite-agent pipeline upload"
