steps:
  - command: ls
    plugins:
      - equinixmetal-buildkite/trivy#v1.18.3:
          timeout : 5m0s
          severity: "HIGH"
          ignore-unfixed: true
          security-checks: "vuln,config"
